### ISSUE TITLE
[Feature Request] Groupable controls with headers

### ISSUE THREAD

**Issue by rurre** [jangxx/VRC-Avatar-Remote-Server#5]
It's hard to get a good board layout going because different screen sizes.

I realize this one would require a bit more work but it would be really nice to have named headers that you can put controls into.
The headers should also be able to be reordered just like you can with controls now.
This would help organize and group stuff, and if you don't want to use groups you can just have a default one, maybe without a name.

![headers](https://user-images.githubusercontent.com/16716633/210184757-15ef1d2f-daa0-46b7-b617-10fc0ecb992d.png)

**Comment by jangxx** [comment]
Good idea! I think the easiest way to add this feature is to just have the headers in between the controls (in the admin interface), so you can move them around like you can controls. The board would then simply render a full-width header instead of a button, which automatically pushes every control after it into a new row.

This implementation is of course different from having actual groups, but I think it's an easy and extendable solution that doesn't require too much reengineering.

**Comment by rurre** [comment]
Sounds good!
Also, if possible I think it would also be nice if the headers would be collapsable, which would hide all controls in that group, but it's not something vital.

**Comment by jangxx** [comment]
Okay, I decided to implement this whole thing "properly" after all. I am mostly done by now - you can see the current state of the feature in the `feature/groups` branch. If you want, you can test it/play around with it now. In case you run into any issues, just write a comment here. I'm gonna be on vacation this week and will take a look at any issues next week when I'm back home.

**Comment by rurre** [comment]
Nice! I've given it a try and have some quick feedback.
- 
- Controls sometimes fail to move on save and give an error. I'm not sure how to reproduce it but the error below. I'm moving things out of the default group on an older avatar instead of creating a new one. [1]
- Controls sometimes fail to move on save but don't give an error. They just don't move.
- The default group should hide itself if it's empty.
- When in editing layout, only the icon, label and grab handle should be displayed on a control because it's easier to move small things around. This is the thing I implemented on my branch before this feature. I'm gonna try to port it over later but I thought it's worth mentioning.

Great job so far!

[1]:
```
Error: Order definition is not valid (ids don't match the ones currently in the group
    at BoardAvatarGroup.setControlOrder (/home/user/VRChat Stuff/VRC-Avatar-Remote-Server-feature-groups/src/board.js:122:10)
    at Board.setGroupControlOrder (/home/user/VRChat Stuff/VRC-Avatar-Remote-Server-feature-groups/src/board.js:554:9)
    at /home/user/VRChat Stuff/VRC-Avatar-Remote-Server-feature-groups/src/routes/admin.js:361:20
    at Layer.handleRequest (/home/user/VRChat Stuff/VRC-Avatar-Remote-Server-feature-groups/node_modules/router/lib/layer.js:101:15)
    at next (/home/user/VRChat Stuff/VRC-Avatar-Remote-Server-feature-groups/node_modules/router/lib/route.js:142:13)
    at /home/user/VRChat Stuff/VRC-Avatar-Remote-Server-feature-groups/node_modules/zod-express-middleware/lib/index.js:88:16
    at Layer.handleRequest (/home/user/VRChat Stuff/VRC-Avatar-Remote-Server-feature-groups/node_modules/router/lib/layer.js:101:15)
    at next (/home/user/VRChat Stuff/VRC-Avatar-Remote-Server-feature-groups/node_modules/router/lib/route.js:142:13)
    at /home/user/VRChat Stuff/VRC-Avatar-Remote-Server-feature-groups/src/board_manager.js:148:10
    at Layer.handleRequest (/home/user/VRChat Stuff/VRC-Avatar-Remote-Server-feature-groups/node_modules/router/lib/layer.js:101:15)
```

**Comment by jangxx** [comment]
>Controls sometimes fail to move on save and give an error. I'm not sure how to reproduce it but the error below. I'm moving things out of the default group on an older avatar instead of creating a new one. [1]

Haha, that was a fun bug to fix. I completely forgot that there were no safeguards in place that kept the board modification endpoints from overwriting each others changes when run at the same time. I added a locking mechanism to enforce strict sequential execution to prevent similar issues in the future now.

>Controls sometimes fail to move on save but don't give an error. They just don't move.

This is hopefully fixed by my first fix.

>The default group should hide itself if it's empty.

Good point, I changed it to where all empty groups are hidden now. Doesn't really make sense to have empty group headers floating around.

>When in editing layout, only the icon, label and grab handle should be displayed on a control because it's easier to move small things around.

After deliberating this a bit, I decided to make this change as well. I don't think this was a massive issue, and I still don't like the fact that the whole interface moves around as much as it does when switching between modes, but I can't argue with the fact that it makes editing boards with a large number of controls significantly more comfortable. So yea, this has also been added now.

**Comment by rurre** [comment]
Good work!

**Comment by jangxx** [comment]
Okay, I merged the group feature now. If there are still problems or other things we can reopen the issue or open a new one.

**Comment by rurre** [comment]
Great! Thanks
________________________________
